image: node:12.13.1
cache:
paths:
  - node_modules/

before_script:
  - npm install
  
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r posts .public
    - cp *.html .public
    - cp *.css .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master